### PR TITLE
Dependency stuff. Fixes #13.

### LINKED ISSUE #13: insecure dependency
Depends on an old version of super-agent, which in turn depended on an old version of qs, which had vulnerabilities. Fixed in qs >=1.x, which is used in newer versions of super-agent.

### PR DESCRIPTION
**Pull request by callumacrae**
Fixes #13.

### CODE REVIEW

**Comment by callumacrae** [comment]
@thomasdavis Is this project still hapenning?

**Comment by nelsonic** [comment]
Hi @thomasdavis the project is still happening, 
the build for the PR you have submitted does not pass in Travis-CI: https://travis-ci.org/thomasdavis/w3cjs/builds/38617513 

also you could update the dependencies to  **2.6.0** for **Commander** and **0.21.0** for **Superagent** if you want the PR merged as per: https://david-dm.org/thomasdavis/w3cjs

Updating the deps will trigger another Travis build and if it passes your PR will be mergeable. :+1:

**Comment by nelsonic** [comment]
Also, given that **Superagent** no longer supports Node **V.0.8** you could suggest a change in https://github.com/thomasdavis/w3cjs/blob/master/.travis.yml#L3 to only support node 0.10. ...

**Comment by thomasdavis** [comment]
Sorry Callum, this PR slipped through the cracks, taking care of it now...

**Comment by thomasdavis** [comment]
Alright those changes should be found on version `0.2.0` https://www.npmjs.com/package/w3cjs

Should probably just remove `superagent` and replace with vanilla javascript...

@nelsonic I've also added you as a contributor, feel free to commit where necessary.

**Comment by callumacrae** [comment]
:+1:

**Comment by thomasdavis** [comment]
Hey @callumacrae curious about your thoughts on jspm.io, yay or nay?

**Comment by callumacrae** [comment]
Never heard of it before. Too many javascript package managers :confounded: I like the look of duojs, but I've never used it.

When I use a package manager, I use npm, because I usually use browserify. Sometimes I'll use cdnjs if I'm just quickly developing something and don't want to mess about with Gulp.

**Comment by thomasdavis** [comment]
Yeah okay, I just like that it's attempting to future proof module loaders for ecma 6.

Will stay in touch!

**Comment by callumacrae** [comment]
Yeah that does look nice. I'm not familiar with ES6 modules, yet, but I'll look at that package manager again when I am (I'm going to London JS Conf next month and there's a talk on it).

**Pull request closed without merging**
