### PR TITLE
Updated to use validator.w3.org/nu/

### PR DESCRIPTION
**Pull request by swillner**
Unfortunately I didn't find anything on how to use the doctype and encoding option in the new validator interface

### CODE REVIEW

**Comment by swillner** [comment]
fixes thomasdavis/w3cjs#17

**Comment by callumacrae** [comment]
Looks good to me! Would be good if we could get the doctype and encoding options back, though.

**Comment by swillner** [comment]
The options don't seem to be available anymore, also the "official" W3C-checker does not support them: http://validator.github.io/validator/
The encoding seems to be auto-detected, but could be provided in the HTTP header (Content-type).
A workaround for the doctype could be simply prepending the document with a "<!doctype ...>"

**Comment by thomasdavis** [comment]
Anyone know which semver I should bump this to?

**Comment by callumacrae** [comment]
Depends if the output has changed. If the output changed, major, otherwise minor.

My guess is that it's a minor release—the tests didn't need changing which suggests the output is the same.

**Comment by callumacrae** [comment]
I'm now getting this from gulp-w3cjs:

```
[15:44:49] HTML Warning: valid.html Line undefined, Column undefined: The Content-Type was “text/html”. Using the HTML parser.
[15:44:49] HTML Warning: valid.html Line undefined, Column undefined: Using the schema for HTML with SVG 1.1, MathML 3.0, RDFa 1.1, and ITS 2.0 support.
```

I didn't get that before. Any ideas how I can get it to go away?

**Comment by swillner** [comment]
That is going to be hidden by default when separating info messages (like these) callumacrae/gulp-w3cjs/pull/11

**Pull request merged**
