### PR TITLE
Hide deprecation message

### PR DESCRIPTION
**Pull request by bfred-it**
Temporary fix

### CODE REVIEW

**Comment by callumacrae** [comment]
Issue in question: #17

Imo it shouldn't be hidden. Is it causing a bug with this library, or is it just annoying?

**Comment by bfred-it** [comment]
I'm using it through gulp-w3cjs and it's annoying, yes, especially when checking a dozen of otherwise valid HTML files. Perhaps we can add a one-off warning instead?

**Comment by bfred-it** [comment]
Or maybe simply…
https://github.com/zrrrzzt/html-validator
https://github.com/hoobdeebla/gulp-html-validator

**Comment by callumacrae** [comment]
`gulp-html-validator` should really be blacklisted because it already exists. Still not sure why people write libraries that already exist instead of contributing to the existing one.

Sigh, Node :disappointed: 

It looks super easy to switch to /nu/: https://github.com/zrrrzzt/html-validator/commit/9d899ff50ed377546d8c82e1fc1a7b11392d7e63

**Comment by bfred-it** [comment]
I tried changing the url but the change is not the equivalent: html5.validator.nu uses the same format as the new url, but not probably not the same as the old w3c url.

I also tried that module and while its tests seem to work, I see no output in the console.

**Pull request closed without merging**
